name: slower-build
on:
  push:
    branches: [ main beta develop ]
  pull_request:
    branches: [ main beta develop ]
env:
  CARGO_TERM_COLOR: always
jobs:
  rust-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose